import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const currentDir = path.dirname(fileURLToPath(import.meta.url));
const sdkRoot = path.resolve(currentDir, "..");
const contractsAbiPath = process.env.COTI_CONTRACT_ABI_PATH
  ? path.resolve(process.env.COTI_CONTRACT_ABI_PATH)
  : path.resolve(sdkRoot, "..", "contracts", "abi", "PrivateAgentMessaging.json");
const outputPath = path.join(sdkRoot, "src", "abi.ts");

const abi = JSON.parse(await readFile(contractsAbiPath, "utf8"));
if (!Array.isArray(abi)) {
  throw new Error(`Expected ABI array in ${contractsAbiPath}`);
}

const contents = `// This file is generated by \`npm run sync:abi -w @coti-agent-messaging/sdk\`.\n` +
  `// Source ABI: ${contractsAbiPath}\n` +
  `export const PRIVATE_AGENT_MESSAGING_ABI = ${JSON.stringify(abi, null, 2)} as const;\n`;

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(outputPath, contents, "utf8");

console.log(`Synced ABI to ${outputPath}`);
